name: autoservice24
description: Auto Service 24 - Car Service Management App

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Network & API
  dio: ^5.4.0

  # Image handling
  image_picker: ^1.0.4

  web_socket_channel: ^2.4.0



  # Storage
  shared_preferences: ^2.2.2

  # UI Components
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.4
  cached_network_image: ^3.3.1


  # Social Authentication
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.3
  sign_in_with_apple: ^6.0.0

  # Maps & Location (if needed)
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0

  # Utils
  intl: ^0.18.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
