android.useAndroidX=true
android.enableJetifier=true

# ??? 16KB page size (????? ???????? ????? ???????)
android.enableAppCompatFor16kbPageSize=true

# ??????? ??????
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx8G -Dfile.encoding=UTF-8
# Align plugin modules that still declare older Java targets
kotlin.jvm.target.validation.mode=warning
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
